# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CleysonWebDev
email: cleysonwebdev@gmail.com
description: Blog pessoal de um desenvolvedor amante de tecnologia, criatividade, inovação e empreendedorismo
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cleysonlb.github.io/"
twitter_username: Cleysonlb
github_username:  Cleysonlb
gems: [jekyll-paginate]
paginate: 1
paginate_path: "pagina-:num"

# Build settings
markdown: kramdown
permalink: /:title/

exclude: ['package.json', 'src', 'node_modules', 'vendor/bundle/ruby']
